/**
 * Analytics and audit — over BRIDGE's own records, never over WhatsApp.
 *
 * The distinction is the whole design. This module reports what *Bridge* did:
 * sends it attempted, sends it refused and the rule that refused them, syncs it
 * ran, extractions it staged, rules that fired. It never reports what is *in*
 * WhatsApp — no message counts scraped from threads, no "who talks to you
 * most", no engagement statistics about other people. Those would require
 * reading the account as an analytics source, which is both a fresh read-volume
 * problem and a category of surveillance the owner did not ask for.
 *
 * So every row here is generated by a Bridge action at the moment it happens.
 * If Bridge has done nothing, the log is empty and the surface says so. There
 * is no backfill, because there is nothing honest to backfill FROM.
 *
 * Residency: Local Plane only. The log records who was messaged and when, which
 * is relationship data in exactly the sense ADR-158 confines to the local tier.
 *
 * Pure: no clock, no RNG, no I/O. Ids and timestamps are supplied by the caller.
 */

import type { OutboundOutcome } from "./outbound.js";
import type { SendPolicyRule } from "./policy.js";

/** The Local Plane state namespace the audit log lives in. */
export const WHATSAPP_AUDIT_NAMESPACE = "whatsapp:audit";

/**
 * How many events are retained.
 *
 * A cap is necessary — this state is one JSON value, rewritten on every append,
 * so an unbounded log would grow the write cost of every future action without
 * limit. When the cap bites, the OLDEST events are dropped and the number
 * dropped is counted, because a log that silently forgets is worse than no log:
 * it invites "there were no refusals" to be read off a window that simply no
 * longer contains them.
 */
export const AUDIT_RETENTION = 2_000;

/**
 * What Bridge did. Every kind is an action Bridge took or declined to take.
 *
 * `rule_fired` and `rule_skipped` belong to the Automation Rules Tool, which
 * writes them through `appendAuditEvent` like everything else. They are part of
 * this vocabulary rather than that Tool's private one so the audit surface has
 * a single answer to "what has happened", and so a reader is not required to
 * know which Tool produced a row in order to find it.
 */
export type AuditEventKind =
  /** A send was proposed and entered the gate. */
  | "send_attempted"
  /** The gate passed it and the shell reported it delivered. */
  | "send_sent"
  /** Refused. Waiting does not fix it. `rule` says which rule. */
  | "send_refused"
  /** Not now. `rule` says why; `earliestAt` when it becomes retryable. */
  | "send_deferred"
  /** A human must approve this recipient before anything is attempted. */
  | "send_needs_approval"
  /** A message-sync pass ran against one chat. */
  | "sync_run"
  /** A Contact Extractor run was staged. */
  | "extraction_run"
  /** An Automation rule matched and started an Agent Run. */
  | "rule_fired"
  /** An Automation rule matched but did not run, e.g. it is disabled. */
  | "rule_skipped"
  /** Automation was halted by the kill switch. */
  | "automation_halted"
  /** A named human re-armed automation. */
  | "automation_rearmed";

/**
 * Structured detail. Deliberately narrow: strings, numbers and booleans only.
 *
 * Message BODIES never go in here. The audit log answers "what did Bridge do",
 * and storing the text alongside would quietly turn it into a second copy of
 * the message store with a different retention rule and no search guard.
 */
export type AuditDetail = Record<string, string | number | boolean>;

export interface AuditEvent {
  id: string;
  kind: AuditEventKind;
  /** ISO-8601, supplied by the caller — this module has no clock. */
  at: string;
  /** What it was about: a chat id, or a `kind:id` annotation subject key. */
  subjectKey?: string;
  /** The recipient key for a send, in its own identity space. */
  recipientKey?: string;
  /** The policy or shell rule that decided a refusal or deferral. */
  rule?: SendPolicyRule | string;
  /** Human-readable, straight from the decision that produced it. */
  reason?: string;
  /** Rule that fired, when this is a rule event. */
  ruleId?: string;
  /** When a deferral becomes retryable. ISO-8601. */
  earliestAt?: string;
  detail?: AuditDetail;
}

export interface AuditState {
  version: 1;
  /** Newest first. */
  events: AuditEvent[];
  /** How many events retention has discarded. Never decreases. */
  dropped: number;
}

export function emptyAuditState(): AuditState {
  return { version: 1, events: [], dropped: 0 };
}

const AUDIT_KINDS: ReadonlySet<string> = new Set<AuditEventKind>([
  "send_attempted",
  "send_sent",
  "send_refused",
  "send_deferred",
  "send_needs_approval",
  "sync_run",
  "extraction_run",
  "rule_fired",
  "rule_skipped",
  "automation_halted",
  "automation_rearmed",
]);

function readDetail(value: unknown): AuditDetail | undefined {
  if (typeof value !== "object" || value === null) return undefined;
  const detail: AuditDetail = {};
  for (const [key, entry] of Object.entries(value)) {
    if (typeof entry === "string" || typeof entry === "number" || typeof entry === "boolean") {
      detail[key] = entry;
    }
  }
  return Object.keys(detail).length > 0 ? detail : undefined;
}

/**
 * Accept an unknown persisted value as audit state, or start fresh.
 *
 * Salvaging rather than all-or-nothing, for the same reason as the annotation
 * reader: these rows are evidence. A single malformed event is skipped and
 * counted as dropped, so the total stays honest instead of the whole log
 * vanishing because one row was written by an older shape.
 */
export function readAuditState(value: unknown): AuditState {
  if (typeof value !== "object" || value === null) return emptyAuditState();
  const candidate = value as Partial<AuditState>;
  if (candidate.version !== 1 || !Array.isArray(candidate.events)) return emptyAuditState();

  const events: AuditEvent[] = [];
  let skipped = 0;
  for (const entry of candidate.events) {
    if (!entry || typeof entry !== "object") {
      skipped += 1;
      continue;
    }
    const row = entry as Partial<AuditEvent>;
    if (
      typeof row.id !== "string" ||
      row.id.length === 0 ||
      typeof row.kind !== "string" ||
      !AUDIT_KINDS.has(row.kind) ||
      typeof row.at !== "string" ||
      row.at.length === 0
    ) {
      skipped += 1;
      continue;
    }
    const detail = readDetail(row.detail);
    events.push({
      id: row.id,
      kind: row.kind as AuditEventKind,
      at: row.at,
      ...(typeof row.subjectKey === "string" ? { subjectKey: row.subjectKey } : {}),
      ...(typeof row.recipientKey === "string" ? { recipientKey: row.recipientKey } : {}),
      ...(typeof row.rule === "string" ? { rule: row.rule } : {}),
      ...(typeof row.reason === "string" ? { reason: row.reason } : {}),
      ...(typeof row.ruleId === "string" ? { ruleId: row.ruleId } : {}),
      ...(typeof row.earliestAt === "string" ? { earliestAt: row.earliestAt } : {}),
      ...(detail ? { detail } : {}),
    });
  }

  const dropped =
    typeof candidate.dropped === "number" && Number.isFinite(candidate.dropped)
      ? Math.max(0, Math.floor(candidate.dropped))
      : 0;
  return { version: 1, events, dropped: dropped + skipped };
}

/**
 * Append one event, newest first, enforcing retention.
 *
 * Appending the same id twice is a no-op. Retries are normal on a send path —
 * a caller that re-runs after a transient failure must not double-count its own
 * refusal into the analytics.
 */
export function appendAuditEvent(
  state: AuditState,
  event: AuditEvent,
  retention: number = AUDIT_RETENTION,
): AuditState {
  if (state.events.some((existing) => existing.id === event.id)) return state;

  const cap = Math.max(1, Math.floor(retention));
  const events = [event, ...state.events];
  const overflow = Math.max(0, events.length - cap);
  return {
    version: 1,
    events: overflow > 0 ? events.slice(0, cap) : events,
    dropped: state.dropped + overflow,
  };
}

/**
 * Turn an outcome from the real outbound gate into the row that records it.
 *
 * This is what keeps the analytics honest: the numbers are not gathered by a
 * separate counter that could drift from what actually happened, they ARE the
 * outbound path's own decisions written down. `performAutomatedSend` returns
 * one of these for every send it processes, and every one becomes a row.
 */
export function auditEventFromOutcome(
  id: string,
  atIso: string,
  recipientKey: string,
  outcome: OutboundOutcome,
  extra: { subjectKey?: string; ruleId?: string } = {},
): AuditEvent {
  const base = {
    id,
    at: atIso,
    recipientKey,
    ...(extra.subjectKey !== undefined ? { subjectKey: extra.subjectKey } : {}),
    ...(extra.ruleId !== undefined ? { ruleId: extra.ruleId } : {}),
  };

  switch (outcome.status) {
    case "sent":
      return {
        ...base,
        kind: "send_sent",
        detail: { delaySeconds: outcome.delaySeconds },
      };
    case "needs_approval":
      return { ...base, kind: "send_needs_approval", reason: outcome.reason };
    case "refused":
      return {
        ...base,
        kind: "send_refused",
        reason: outcome.reason,
        ...(outcome.code !== undefined ? { rule: outcome.code } : {}),
      };
    case "deferred":
      return {
        ...base,
        kind: "send_deferred",
        reason: outcome.reason,
        ...(outcome.code !== undefined ? { rule: outcome.code } : {}),
        ...(outcome.earliestAtMs !== undefined
          ? { earliestAt: new Date(outcome.earliestAtMs).toISOString() }
          : {}),
      };
  }
}

export interface AuditQuery {
  kinds?: readonly AuditEventKind[];
  subjectKey?: string;
  ruleId?: string;
  /** Inclusive lower bound, ISO-8601. */
  sinceIso?: string;
  limit?: number;
}

/** Filtered events, newest first. Empty when nothing matches — never padded. */
export function listAuditEvents(state: AuditState, query: AuditQuery = {}): AuditEvent[] {
  const kinds = query.kinds ? new Set<string>(query.kinds) : null;
  const since = query.sinceIso ? Date.parse(query.sinceIso) : Number.NaN;

  const matched = state.events.filter((event) => {
    if (kinds && !kinds.has(event.kind)) return false;
    if (query.subjectKey !== undefined && event.subjectKey !== query.subjectKey) return false;
    if (query.ruleId !== undefined && event.ruleId !== query.ruleId) return false;
    if (!Number.isNaN(since)) {
      const at = Date.parse(event.at);
      if (Number.isNaN(at) || at < since) return false;
    }
    return true;
  });

  const limit = query.limit;
  return limit !== undefined && limit >= 0 ? matched.slice(0, limit) : matched;
}

export interface AuditSummary {
  /** Events considered, after the window filter. */
  total: number;
  /** How many retention has discarded, so a zero can be read correctly. */
  dropped: number;
  /** The oldest and newest event actually held. Absent when the log is empty. */
  earliestAt?: string;
  latestAt?: string;
  /** Count per kind. Only kinds that actually occurred appear. */
  byKind: { kind: AuditEventKind; count: number }[];
  /**
   * Why sends did not go out, most frequent first. The question the owner
   * actually has when a campaign is quieter than expected.
   */
  refusalsByRule: { rule: string; count: number; reason: string }[];
  /** Sends that entered the gate, and what became of them. */
  sends: {
    attempted: number;
    sent: number;
    refused: number;
    deferred: number;
    needsApproval: number;
  };
}

/**
 * Roll the log up. Reports only what is in it.
 *
 * `total` counts the events in the window, and `dropped` is reported alongside
 * rather than folded in, so "0 refusals" can be distinguished from "refusals
 * that retention has already discarded".
 */
export function summarizeAudit(
  state: AuditState,
  query: Pick<AuditQuery, "sinceIso"> = {},
): AuditSummary {
  const events = listAuditEvents(state, query);

  const byKind = new Map<AuditEventKind, number>();
  const refusals = new Map<string, { count: number; reason: string }>();
  for (const event of events) {
    byKind.set(event.kind, (byKind.get(event.kind) ?? 0) + 1);
    if (event.kind === "send_refused" || event.kind === "send_deferred") {
      const rule = event.rule ?? "unspecified";
      const existing = refusals.get(rule);
      refusals.set(rule, {
        count: (existing?.count ?? 0) + 1,
        // The first reason seen for a rule. They are generated from the same
        // template per rule, so the first is representative.
        reason: existing?.reason ?? event.reason ?? "",
      });
    }
  }

  // `events` is newest first, so the ends are the bounds.
  const latest = events[0]?.at;
  const earliest = events[events.length - 1]?.at;

  return {
    total: events.length,
    dropped: state.dropped,
    ...(earliest !== undefined ? { earliestAt: earliest } : {}),
    ...(latest !== undefined ? { latestAt: latest } : {}),
    byKind: [...byKind.entries()]
      .map(([kind, count]) => ({ kind, count }))
      .sort((a, b) => (b.count - a.count) || a.kind.localeCompare(b.kind)),
    refusalsByRule: [...refusals.entries()]
      .map(([rule, entry]) => ({ rule, count: entry.count, reason: entry.reason }))
      .sort((a, b) => (b.count - a.count) || a.rule.localeCompare(b.rule)),
    sends: {
      attempted: byKind.get("send_attempted") ?? 0,
      sent: byKind.get("send_sent") ?? 0,
      refused: byKind.get("send_refused") ?? 0,
      deferred: byKind.get("send_deferred") ?? 0,
      needsApproval: byKind.get("send_needs_approval") ?? 0,
    },
  };
}
