import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

const pageSource = await readFile(new URL("../src/app/pages/DealPilotPage.tsx", import.meta.url), "utf8");
const routeSource = await readFile(new URL("../src/app/routes.tsx", import.meta.url), "utf8");

test("DealPilot exposes exactly the Deals, Sources, and Theses default Page routes", () => {
  assert.match(routeSource, /dealpilot\/:page/);
  assert.match(routeSource, /dealpilot\/:page\/:recordId/);
  assert.match(pageSource, /deals: \{ label: "Deals"/);
  assert.match(pageSource, /sources: \{ label: "Sources"/);
  assert.match(pageSource, /theses: \{ label: "Theses"/);
  for (const forbidden of ["Overview", "Summary", "Reports"]) {
    assert.doesNotMatch(pageSource, new RegExp(`label: "${forbidden}"`));
  }
});

test("DealPilot uses real tRPC Records and honest empty states without runtime fixture storage", () => {
  assert.match(pageSource, /trpc\.dealpilot\.records\.query/);
  assert.match(pageSource, /No \{page\} yet/);
  assert.match(pageSource, /Exports and briefs generated by DealPilot will show up here/);
  assert.doesNotMatch(pageSource, /localStorage|dummy_|test_fixture_|DEFAULT_THESIS|LISTINGS/);
});

test("Source credentials require re-authentication and are never persisted by the page", () => {
  assert.match(pageSource, /supabase\.auth\.signInWithPassword/);
  assert.match(pageSource, /reauthenticateCredential/);
  assert.match(pageSource, /accessCredential/);
  assert.match(pageSource, /navigator\.clipboard\.writeText/);
  assert.match(pageSource, /window\.setTimeout/);
  assert.doesNotMatch(pageSource, /sessionStorage|localStorage/);
});

test("DealPilot surfaces governed Thesis and Source discovery", () => {
  assert.match(pageSource, /trpc\.action\.decide\.mutate/);
  assert.match(pageSource, /effectsStatus === "failed"/);
  assert.match(pageSource, /discoverDeals/);
  assert.match(pageSource, /disabled=\{discovering\}/);
  assert.match(pageSource, /Quarantined Deal candidates/);
  assert.match(pageSource, /trpc\.dealpilot\.commit/);
});

test("route-bound DealPilot reads discard stale responses", () => {
  assert.match(pageSource, /loadGeneration\.current === generation/);
  assert.match(pageSource, /currentRouteKey\.current === expectedRouteKey/);
  assert.match(pageSource, /loadGeneration\.current \+= 1/);
  assert.match(pageSource, /setDetail\(null\)/);
  assert.match(pageSource, /setCaptures\(\[\]\)/);
});

test("DealPilot loads every Record page rather than hiding rows after the first API page", () => {
  assert.match(pageSource, /async function queryAllRecords/);
  assert.match(pageSource, /while \(current\.hasMore && current\.items\.length > 0\)/);
  assert.match(pageSource, /offset: items\.length/);
});
