export {
  BUILT_IN_MODULES,
  CITED_ROLE_MODEL_PRACTICE_VERSION,
  COMMONS_BUILT_IN_MODULES,
  DEALPILOT_SOURCE_AUTOMATION_ID,
  DEALPILOT_SOURCE_AUTOMATION_KEY,
  DEALPILOT_SOURCING_AGENT_ID,
  LEARNING_AGENT_RUNTIME_ID,
  LEARNING_RECOMMENDATION_SKILL_ID,
  GOVERNANCE_AGENT_RUNTIME_ID,
  INTERNAL_STRATEGIST_AGENT_RUNTIME_ID,
  TASK_MANAGER_DRIFT_AUTOMATION_ID,
  TASK_MANAGER_SWEEP_AUTOMATION_ID,
  buildModuleNavTree,
  isModuleRuntimeAutomationId,
  requireBuiltInModule,
  resolveModuleAgentRuntimeId,
  resolveModuleAutomationRuntimeId,
  type BuiltInModule,
  type CommonsBuiltInModule,
  type ModuleNavNode,
  type NavModuleLike,
} from "@bridge/module-manifests";
