export {
  BUILT_IN_MODULES,
  CITED_ROLE_MODEL_PRACTICE_VERSION,
  COMMONS_BUILT_IN_MODULES,
  DEALPILOT_SOURCE_AUTOMATION_ID,
  DEALPILOT_SOURCE_AUTOMATION_KEY,
  DEALPILOT_SOURCING_AGENT_ID,
  LEARNING_AGENT_RUNTIME_ID,
  LEARNING_RECOMMENDATION_SKILL_ID,
  isModuleRuntimeAutomationId,
  requireBuiltInModule,
  resolveModuleAgentRuntimeId,
  resolveModuleAutomationRuntimeId,
  type BuiltInModule,
  type CommonsBuiltInModule,
} from "@bridge/module-manifests";
